export const DefaultThemes = [
  { name: 'light-blue', header: { bg: '#e8f2fe', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#f8fbff' } },
  { name: 'light-grey', header: { bg: '#f4f4f4', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fafafa' } },
  { name: 'light-red', header: { bg: '#ffe8e8', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fff8f8' } },
  { name: 'light-orange', header: { bg: '#fff0e0', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fffcf8' } },
  { name: 'light-yellow', header: { bg: '#fffde0', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fffef9' } },
  { name: 'light-green', header: { bg: '#e0ffe8', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fafffc' } },
  { name: 'light-azure', header: { bg: '#e0ffff', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#f7ffff' } },
  { name: 'light-indigo', header: { bg: '#ebe0ff', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#faf7ff' } },
  { name: 'light-purple', header: { bg: '#fbd0ff', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fef7ff' } },
  { name: 'light-magenta', header: { bg: '#ffe0f5', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffffff' }, bodyOdd: { bg: '#fff7fc' } },

  { name: 'middle-blue', header: { bg: '#a3c9ff', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#e8f2fe' }, bodyOdd: { bg: '#d4e6fc' } },
  { name: 'middle-grey', header: { bg: '#dcdcdc', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#f4f4f4' }, bodyOdd: { bg: '#eaeaea' } },
  { name: 'middle-red', header: { bg: '#ffaaaa', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffe8e8' }, bodyOdd: { bg: '#ffd4d4' } },
  { name: 'middle-orange', header: { bg: '#ffccaa', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#fff0e0' }, bodyOdd: { bg: '#ffe0cc' } },
  { name: 'middle-yellow', header: { bg: '#ffeaa0', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#fffde0' }, bodyOdd: { bg: '#fff8c0' } },
  { name: 'middle-green', header: { bg: '#aadcb3', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#e0ffe8' }, bodyOdd: { bg: '#ccf2d9' } },
  { name: 'middle-azure', header: { bg: '#a0e8e8', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#e0ffff' }, bodyOdd: { bg: '#d0f8f8' } },
  { name: 'middle-indigo', header: { bg: '#bfaaff', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ebe0ff' }, bodyOdd: { bg: '#dccaff' } },
  { name: 'middle-purple', header: { bg: '#e8a0ff', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#fbd0ff' }, bodyOdd: { bg: '#f5c0ff' } },
  { name: 'middle-magenta', header: { bg: '#ffaadd', color: '#000000', fontWeight: 'bold' }, bodyEven: { bg: '#ffe0f5' }, bodyOdd: { bg: '#ffcced' } },

  { name: 'dark-blue', header: { bg: '#3366cc', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#a3c9ff' }, bodyOdd: { bg: '#85b3f2' } },
  { name: 'dark-grey', header: { bg: '#666666', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#dcdcdc' }, bodyOdd: { bg: '#bfbfbf' } },
  { name: 'dark-red', header: { bg: '#cc3333', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#ffaaaa' }, bodyOdd: { bg: '#ff8888' } },
  { name: 'dark-orange', header: { bg: '#dd7700', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#ffccaa' }, bodyOdd: { bg: '#ffaa66' } },
  { name: 'dark-yellow', header: { bg: '#ddaa00', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#ffeaa0' }, bodyOdd: { bg: '#ffd560' } },
  { name: 'dark-green', header: { bg: '#228844', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#aadcb3' }, bodyOdd: { bg: '#88cc99' } },
  { name: 'dark-azure', header: { bg: '#00aaaa', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#a0e8e8' }, bodyOdd: { bg: '#70d8d8' } },
  { name: 'dark-indigo', header: { bg: '#5533cc', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#bfaaff' }, bodyOdd: { bg: '#9977dd' } },
  { name: 'dark-purple', header: { bg: '#8822cc', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#e8a0ff' }, bodyOdd: { bg: '#cc70ff' } },
  { name: 'dark-magenta', header: { bg: '#aa0088', color: '#ffffff', fontWeight: 'bold' }, bodyEven: { bg: '#ffaadd' }, bodyOdd: { bg: '#ff88cc' } }
];
